name: sistema_jugueteria_efrain_v3
description: Sistema de control y gestión de productos de Juguetería Efraín.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-94.0.dev <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`.
dependencies:
  flutter:
    sdk: flutter
  davi: ^3.4.0
  dio: ^5.3.2
  dropdown_search: ^5.0.6
  elegant_notification: ^1.10.1
  fade_shimmer: ^2.2.0
  file_selector: ^1.0.0
  flutter_riverpod: ^2.3.6
  flutter_switch: ^0.3.2
  flutter_simple_treeview: ^3.0.2
  http: ^1.1.0
  mailto: ^2.0.0
  material_design_icons_flutter: ^7.0.7296
  mysql1: ^0.20.0
  path_provider: ^2.0.15
  pluto_menu_bar: ^3.0.1
  reactive_flutter_typeahead: ^2.0.0
  reactive_forms: ^16.0.2
  shared_preferences: ^2.2.0
  syncfusion_flutter_pdfviewer: ^22.1.39
  tabbed_view: ^1.17.0
  url_launcher: ^6.1.12

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  #  - images/
    - json/
  #  - fonts/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg